site_name: DCS Documentation Centralized
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/en/docs
site_author: "rost.lunegoff@gmail.com"
extra:
  analytics:
    provider: google
    property: UA-19502035-4
  social:
    - icon: fontawesome/brands/telegram
      link: /to-telega
      name: Пишите в Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:rost.lunegoff@gmail.com

nav:
  - About:
      - index.md
      - help.md
      - people.md
  - Docs:
    - Supercarrier by ED:
      - sc/01.quickstart.md
      - sc/02.nimitz.md
      - sc/03.launch.md
      - sc/04.recovery.md
      - sc/05.lso.md
      - sc/06.editor.md
      - sc/07.glossary.md
    - F-16C Viper by ED:
      - f16/01.history.md
      - f16/02.stores.md
      - f16/03.cockpit.md
      - f16/04.hotas.md

theme:
  name: material
  language: ru
  font:
    text: 'Roboto Slab'
    code: 'Fira Mono'
    #  palette:
    #    primary: black
    #    accent: blue
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
      # - navigation.indexes

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
        full_path_in_title: yes
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
  - mdx_superscript
  - markdown_captions
  - markdown_include.include
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - abbr
  - kbdextension:
      brackets_css: keyboard-css
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

