site_name: DCS Documentation Centralized
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/ru/docs
google_analytics: ['UA-19502035-4', 'auto']
site_author: "rost.lunegoff@gmail.com"
copyright: "<a href=https://t.me/rlunegov>Telegram</a>"

nav:
  - О проекте:
      - index.md
      - help.md
      - people.md

#theme: readthedocs
theme:
  name: material
  language: ru
  font:
    text: 'Roboto Slab'
    code: 'Fira Mono'
  palette:
    primary: indigo
    accent: blue
  features:
    - instant

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
  - mdx_superscript
  - markdown_captions
  - markdown_include.include
  - admonition
  - abbr
  - kbdextension:
      brackets_css: keyboard-css
