site_name: DCS Documentation Centralized
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/ru/docs

nav:
  - index.md
  - "ВМВ":
      - i16.md
      - fw190a8.md
  - tags.md

#theme: readthedocs
theme:
  name: material
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    primary: 'blue grey'
    accent: blue
  features:
    - instant

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
  - mdx_superscript
  - markdown_captions
