site_name: Документация DCS
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/ru/docs
google_analytics: ['UA-19502035-4', 'dcs-docs.lordvesel.win/ru/']
site_author: "rost.lunegoff@gmail.com"
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/rlunegov
      name: Пишите в Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:rost.lunegoff@gmail.com
nav:
  - О проекте:
      - index.md
      - help.md
      - people.md
  - Документация:
# - Вторая Мировая:
      - i16.md
      - FW-190 A8 от ED:
        - fw190a8/01.intro.md
        - fw190a8/02.history.md
        - fw190a8/03.design.md
        - fw190a8/04.cockpit.md
        - fw190a8/05.stdprocs.md
        - fw190a8/06.emergency.md
        - fw190a8/07.combat.md
        - fw190a8/08.radio.md
        - fw190a8/09.credits.md
      - P-47D от ED:
        - p-47/01.intro.md
        - p-47/02.history.md
        - p-47/03.design.md
        - p-47/04.cockpit.md
        - p-47/05.limits.md
        - p-47/06.procedures.md
        - p-47/07.emergency.md
        - p-47/08.combat.md
        - p-47/10.supplements.md
      - Spitfire Mk. IX от ED:
        - spitfire-ix/01.intro.md
        - spitfire-ix/02.common.md
        - spitfire-ix/03.cockpit.md
        - spitfire-ix/04.design.md
        - spitfire-ix/05.power.md
        - spitfire-ix/06.systems.md
        - spitfire-ix/07.flight.md
        - spitfire-ix/08.arms.md
        - spitfire-ix/09.supplements.md
# - Современная авиация:
      - F/A-18C от ED:
        - fa18c/01.setup.md
        - fa18c/02.cockpit.md
        - fa18c/03.mfdu.md
        - fa18c/04.hud.md
        - fa18c/05.procedures.md
        - fa18c/06.radios.md
        - fa18c/07.modes.md
        - fa18c/08.nav-mode.md
        - fa18c/09.a-g-mode.md
        - fa18c/10.a-a-mode.md
        - fa18c/11.counter-measures.md
        - fa18c/12.ew.md
        - fa18c/13.credits.md
      - Су-25Т от ED:
        - su25t/01.intro.md
        - su25t/02.simple.md
        - su25t/03.cockpit.md
        - su25t/04.radio.md
        - su25t/05.model.md
        - su25t/06.combat.md
# - Вертолёты:
      - Ми-8 от Belsimtek:
        - mi8/01.history.md
        - mi8/02.geninfo.md
        - mi8/03.dynamic.md
        - mi8/04.powerplant.md
        - mi8/05.cockpit.md
        - mi8/06.radios.md
        - mi8/07.systems.md
        - mi8/08.restrictions.md
        - mi8/09.flights.md
        - mi8/10.emergency.md
        - mi8/11.weapons.md
        - mi8/12.engagement.md
        - mi8/13.specialtasks.md
        - mi8/15.abbr.md
        - mi8/17.credits.md
        - mi8/18.sources.md
      - NS430 от Belsimtek:
        - ns430/01.controls.md
        - ns430/02.usage.md
        - ns430/03.pages.md
        - ns430/04.supplement.md

#theme: readthedocs
theme:
  name: material
  language: ru
  font:
    text: 'Roboto Slab'
    code: 'Fira Mono'
    #  palette:
    #    primary: black
    #    accent: blue
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
      # - navigation.indexes

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
  - mdx_superscript
  - markdown_captions
  - markdown_include.include
  - admonition
  - pymdownx.details
  - abbr
  - kbdextension:
      brackets_css: keyboard-css
  - meta
