site_name: DCS Documentation Centralized
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/ru/docs
google_analytics: ['UA-19502035-4', 'dcs-docs.lordvesel.win/ru/']
site_author: "rost.lunegoff@gmail.com"
copyright: "<a href=https://t.me/rlunegov>Пишите в Telegram</a>"

nav:
  - О проекте:
      - index.md
      - help.md
      - people.md
        #  - Вторая Мировая:
        #      - i16.md
        #      - FW-190 A8 от ED:
        #        - fw190a8/01.intro.md
        #        - fw190a8/02.history.md
        #        - fw190a8/03.design.md
        #        - fw190a8/04.cockpit.md
        #        - fw190a8/05.stdprocs.md
        #        - fw190a8/06.emerg.md
        #        - fw190a8/07.combat.md
        #  - Современная авиация:
        #      - F/A-18C от ED:
        #        - fa18c/01.setup.md
        #        - fa18c/02.cockpit.md
        #        - fa18c/03.mfdu.md
        #        - fa18c/04.hud.md
        #        - fa18c/05.procedures.md
        #        - fa18c/06.radios.md
        #        - fa18c/07.modes.md
        #        - fa18c/08.nav-mode.md
        #        - fa18c/09.a-g-mode.md
        #        - fa18c/10.a-a-mode.md
        #        - fa18c/11.counter-mesures.md
        #        - fa18c/12.ew.md
        #        - fa18c/13.credits.md
  - Вертолёты:
      - Ми-8 от Belsimtek:
        - mi8/01.history.md
        - mi8/02.geninfo.md
        - mi8/03.dynamic.md
        - mi8/04.powerplant.md
        - mi8/05.cockpit.md
        - mi8/06.radios.md

#theme: readthedocs
theme:
  name: material
  language: ru
  font:
    text: 'Roboto Slab'
    code: 'Fira Mono'
  palette:
    primary: indigo
    accent: blue
  features:
    - instant

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
  - mdx_superscript
  - mdx_subscript
  - markdown_captions
  - markdown_include.include
  - admonition
  - abbr
  - kbdextension:
      brackets_css: keyboard-css
