site_name: DCS Documentation Centralized
repo_url: https://github.com/lord-vesel/dcs-doc
repo_name: lord-vesel/dcs-doc
edit_uri: edit/develop/ru/docs

nav:
  - index.md
  - Вторая Мировая:
      - i16.md
      - FW-190 A8 от ED:
        - fw190a8/01.intro.md
        - fw190a8/02.history.md
        - fw190a8/03.design.md
        - fw190a8/04.cockpit.md
        - fw190a8/05.stdprocs.md
        - fw190a8/06.emerg.md
        - fw190a8/07.combat.md
  - Современная авиация:
      - F/A-18C от ED:
          - fa18c/01.cockpit.md

#theme: readthedocs
theme:
  name: material
  language: ru
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    primary: indigo
    accent: blue
  features:
    - instant

extra_css:
  - css/materal-add.css
plugins:
    - search:
        lang: ['en', 'ru']
    - tags

markdown_extensions:
  - toc:
      baselevel: 1
  - mdx_superscript
  - markdown_captions
  - admonition
