name: Build DCS docs

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ru/requirements.txt
    - name: Build ru site
      run: |
        cd ru
        mkdocs build
        ls -al
    - name: Upload
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        src: ru/site/
        dest: gh-dcs-deploy@lordvesel.win:/var/www/dcs-docs/dev/

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
