name: Build DCS docs

on:
  push:
    branches: [ develop, fa18 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      DEPLOY_USER: gh-dcs-deploy
      DEPLOY_HOST: lordvesel.win
      RELEASE_DIR: /var/www/dcs-docs/${{ github.ref }}/releases/${{ github.run_number }}
      CURRENT_DIR: /var/www/dcs-docs/${{ github.ref }}/ru
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ru/requirements.txt
    - name: Build ru site
      run: |
        cd ru
        mkdocs build
        ls -al

    - name: Prepare environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          [[ -d ${{env.RELEASE_DIR}} ]] || mkdir -p ${{env.RELEASE_DIR}}

    - name: Upload
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        src: ru/site/
        dest: ${{env.DEPLOY_USER}}@${{env.DEPLOY_HOST}}:${{env.RELEASE_DIR}}

    - name: Switch release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DEPLOY_HOST}}
        username: ${{env.DEPLOY_USER}}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          ln -sfn ${{env.RELEASE_DIR}} ${{env.CURRENT_DIR}}

