name: Build STAGE

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      DEPLOY_USER: gh-dcs-deploy
      DEPLOY_HOST: lordvesel.win
      RELEASE_DIR: /var/www/dcs-docs/stage/releases/${{ github.run_number }}
      RELEASES_DIR: /var/www/dcs-docs/stage/releases/
      CURRENT_DIR: /var/www/dcs-docs/stage/current
    runs-on:
      - self-hosted
      - dcs

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build mkdocs
        run: |
          docker run -i --rm -v $PWD:/build -w /build python:3.10-alpine sh -c 'apk add git gcc linux-headers musl-dev && \
          cd ru && pip install -r requirements.txt && \
          curl -L https://github.com/mikefarah/yq/releases/download/v4.27.3/yq_linux_amd64 -o /usr/bin/yq && \
          chmod +x /usr/bin/yq && \
          mkdocs build && \
          cd ../en && mkdocs build && \
          chown -R 1004:1004 ../'

      - name: Deploy
        run: |
          [[ -d ${{env.RELEASE_DIR}}/ru ]] || mkdir -p ${{env.RELEASE_DIR}}/ru
          [[ -d ${{env.RELEASE_DIR}}/en ]] || mkdir -p ${{env.RELEASE_DIR}}/en
          rsync -a ru/site/ ${{env.RELEASE_DIR}}/ru/
          rsync -a en/site/ ${{env.RELEASE_DIR}}/en/

      - name: CSS
        run: |
          export T=$(date +%s)
          export CSS=css/materal-add-${T}.css
          for L in ru en
          do
            yq -i '.extra_css[0] = strenv(CSS)' $L/mkdocs.yml
            mv $L/docs/css/materal-add.css $/docs/$CSS
          done

      - name: Switch release
        run: |
          ln -sfn ${{env.RELEASE_DIR}} ${{env.CURRENT_DIR}}
          for R in `ls ${{env.RELEASES_DIR}} | sort -n | head -n -1`
          do rm -rf ${{env.RELEASES_DIR}}$R
          done

      - name: Status Success Notification
        if: ${{ success() }}
        run: |
          ntfy -b telegram send "⚡ GITHUB: Successfuly deployed STAGE from ${{ github.head_ref }}. Check out
          https://dcs-docs-stage.lordvesel.win/ru/
          https://dcs-docs-stage.lordvesel.win/en/"

      - name: Status Fail Notification
        if: ${{ failure() }}
        run: |
          ntfy -b telegram send "💩 GITHUB: Deploy STAGE failed from ${{ github.head_ref }}."
