name: Build DEV

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    env:
      DEPLOY_USER: gh-dcs-deploy
      DEPLOY_HOST: lordvesel.win
      RELEASE_DIR: /var/www/dcs-docs/dev/releases/${{ github.ref }}/${{ github.run_number }}
      RELEASES_DIR: /var/www/dcs-docs/dev/releases/
      CURRENT_DIR: /var/www/dcs-docs/dev/current
    runs-on:
      - self-hosted
      - dcs

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare a python virtualenv
      run: |
        python -m venv ~/.virtualenvs/dev
        source ~/.virtualenvs/dev/bin/activate
        pip install -r ru/requirements.txt

    - name: Build RU site
      run: |
        cd $GITHUB_WORKSPACE/ru
        mkdocs build
        ls -al

    - name: Build EN site
      run: |
        cd $GITHUB_WORKSPACE/en
        mkdocs build
        ls -al

    - name: Deploy
      run: |
        [[ -d ${{env.RELEASE_DIR}}/ru ]] || mkdir -p ${{env.RELEASE_DIR}}/ru
        [[ -d ${{env.RELEASE_DIR}}/en ]] || mkdir -p ${{env.RELEASE_DIR}}/en
        rsync -a ru/site/ ${{env.RELEASE_DIR}}/ru/
        rsync -a en/site/ ${{env.RELEASE_DIR}}/en/

    - name: Switch release
      run: |
        ln -sfn ${{env.RELEASE_DIR}} ${{env.CURRENT_DIR}}
        for R in `ls ${{env.RELEASES_DIR}} | sort -n | head -n -3`
        do rm -rf ${{env.RELEASES_DIR}}/$R
        done
