name: Build TEST

on:
  push:
    branches:
      - wkflw

jobs:
  env:
    IMAGE_PHP: registry.p5s-dev.ru/atom/php-fpm:${{ github.sha }}
  build:
    env:
      DEPLOY_USER: gh-dcs-deploy
      DEPLOY_HOST: lordvesel.win
      RELEASE_DIR: /var/www/dcs-docs/dev/releases/${{ github.ref }}/${{ github.run_number }}
      RELEASES_DIR: /var/www/dcs-docs/dev/releases/
      CURRENT_DIR: /var/www/dcs-docs/dev/current
    runs-on:
      - self-hosted
      - dcs

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build mkdocs
      env:
        VARZA: "${{ env.RELEASE_DIR }}: ${{ env.IMAGE_PHP }}"
      run: |
        echo $IMAGE_PHP
        echo $VARZA
